import Link from "next/link";

const capabilities = [
  ["Agent registry", "Maintain a clear inventory of every agent, owner-facing role, model, lifecycle, and risk level."],
  ["Governed access", "Review approved tools and registered knowledge sources before agents enter business workflows."],
  ["Execution monitoring", "Track outcomes, human-review flags, latency, estimated cost, and optional tool evidence."],
  ["Audit timeline", "Follow workspace activity in one chronological operational record."],
];

export default function Home() {
  return <main className="min-h-screen bg-slate-950 text-white">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><Link href="/" className="text-xl font-bold">AIMS<span className="text-indigo-400">.</span></Link><div className="flex items-center gap-3"><Link href="/login" className="text-sm font-semibold text-slate-300 hover:text-white">Sign in</Link><Link href="/login" className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-slate-100">Create workspace</Link></div></nav>
    <section className="mx-auto grid max-w-6xl gap-14 px-6 pb-20 pt-16 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:pb-28 lg:pt-24">
      <div><p className="mb-5 text-sm font-semibold uppercase tracking-[0.25em] text-indigo-400">AI Agent Operations Control Plane</p><h1 className="max-w-4xl text-5xl font-bold tracking-tight sm:text-6xl">Operate AI agents with visibility and control.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">AIMS gives applied AI and platform teams one workspace to inventory agents, govern access, and review execution evidence—without replacing their agent runtime.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="rounded-lg bg-indigo-500 px-5 py-3 font-semibold hover:bg-indigo-400">Open your workspace</Link><a href="#capabilities" className="rounded-lg border border-slate-700 px-5 py-3 font-semibold hover:bg-slate-900">Explore capabilities</a></div><p className="mt-5 text-sm text-slate-500">Built for applied AI engineers, platform teams, and operations reviewers.</p></div>
      <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-widest text-slate-500">Operational workflow</p><h2 className="mt-3 text-xl font-semibold">From inventory to evidence</h2><ol className="mt-5 space-y-3">{["Register agents and classify risk", "Approve tools and knowledge sources", "Log execution outcomes and review flags", "Inspect fleet health and audit activity"].map((item, index) => <li key={item} className="flex items-center gap-3 rounded-lg border border-slate-800 bg-slate-950/60 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-indigo-500/15 text-xs font-bold text-indigo-300">{index + 1}</span><span className="font-medium text-slate-200">{item}</span></li>)}</ol></div>
    </section>
    <section id="capabilities" className="border-y border-slate-800 bg-slate-900/40"><div className="mx-auto max-w-6xl px-6 py-20"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-400">One operational view</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-tight">Know what can act, what it can access, and how it performed.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-400">Fragmented spreadsheets and runtime logs make ownership, risk, and failures difficult to review. AIMS connects the core operational records while keeping governance claims grounded in recorded evidence.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{capabilities.map(([title, description]) => <article key={title} className="rounded-xl border border-slate-800 bg-slate-950/60 p-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p></article>)}</div></div></section>
    <footer className="mx-auto flex max-w-6xl flex-col gap-5 px-6 py-12 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">Ready to review your agent operations?</p><p className="mt-1 text-sm text-slate-400">Create an account or sign in to continue to the protected workspace.</p></div><Link href="/login" className="w-fit rounded-lg bg-indigo-500 px-5 py-3 font-semibold hover:bg-indigo-400">Get started</Link></footer>
  </main>;
}
